import './globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@flaticon/flaticon-uicons/css/all/all.css';
import { BusinessLogicProvider } from '@modules/business-logic/provider';
import { AppReduxProvider } from '@storages/redux';
import MainTemplate from '@presentational/templates/MainTemplate';

const montserrat = Montserrat({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'The New Dawn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <BusinessLogicProvider>
          <AppReduxProvider>
            <MainTemplate>{children}</MainTemplate>
          </AppReduxProvider>
        </BusinessLogicProvider>
      </body>
    </html>
  );
}
