import Header from "@/components/organisms/Header/Header";
import "./globals.scss";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Footer from "@/components/organisms/Footer/Footer";
import "@flaticon/flaticon-uicons/css/all/all.css";
import { BusinessLogicProvider } from "@/modules/business-logic/provider";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The New Dawn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <BusinessLogicProvider>
          <Header />
          {children}
          <Footer />
        </BusinessLogicProvider>
      </body>
    </html>
  );
}
