import { PAGE_URLS } from "@/constants/pages";

export const BASIC_WEB_FLOW = [
  [PAGE_URLS.HOME, PAGE_URLS.SHOP, PAGE_URLS.PRODUCT, PAGE_URLS.CART],
  [PAGE_URLS.HOME, PAGE_URLS.ME],
  [PAGE_URLS.HOME, PAGE_URLS.GUIDE],
  [PAGE_URLS.HOME, PAGE_URLS.CART],
  [PAGE_URLS.HOME, PAGE_URLS.PRICING],
  [PAGE_URLS.HOME, PAGE_URLS.PRODUCT],
  [PAGE_URLS.HOME, PAGE_URLS.ACTIVATE_DEVICE],
  [PAGE_URLS.HOME, PAGE_URLS.ABOUT],
];
